#! /bin/sh

sxhkd &

bspc monitor -d >_ 

compton --config ~/nordrice/compton.conf &

feh --bg-fill ~/nordrice/bg.jpg &

polybar example &

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color		"#2E3440"
bspc config active_border_color		"#D8DEE9"
bspc config focused_border_color	"#D8DEE9"
bspc config presel_feedback_color	"#2E3440"
